name: habitin
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  cloud_firestore: ^4.4.3
  collection: ^1.17.0
  firebase_auth: ^4.2.9
  firebase_core: ^2.7.0
  fl_chart: ^0.61.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.12.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.2.0
  flutter_slidable: ^2.0.0
  intl: ^0.17.0
  json_annotation: ^4.8.0
  shared_preferences: ^2.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

  fonts:    
    - family: ProductSans
      fonts: 
        - asset: assets/fonts/ProductSans-Black.ttf
        - asset: assets/fonts/ProductSans-Bold.ttf
        - asset: assets/fonts/ProductSans-Light.ttf
        - asset: assets/fonts/ProductSans-Medium.ttf
        - asset: assets/fonts/ProductSans-Regular.ttf
